"""empty message

Revision ID: 1eaa24662388
Revises: 46f7b720df1b
Create Date: 2020-09-22 16:45:48.391708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1eaa24662388'
down_revision = '46f7b720df1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=16), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('user', 'salt')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
