"""empty message

Revision ID: 40f9ee3804bb
Revises: ef514f83e021
Create Date: 2020-10-06 02:08:07.339773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40f9ee3804bb'
down_revision = 'ef514f83e021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet', 'winner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('winner', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
