"""empty message

Revision ID: 46f7b720df1b
Revises: 90a9c72184db
Create Date: 2020-09-22 01:07:26.155572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46f7b720df1b'
down_revision = '90a9c72184db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('ludos', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=25), nullable=True))
    op.add_column('user', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'status')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    op.drop_column('user', 'ludos')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
