"""empty message

Revision ID: ab462c5f0c15
Revises: 4ed7fbcc09d6
Create Date: 2020-10-01 01:04:26.955317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab462c5f0c15'
down_revision = '4ed7fbcc09d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('bet', sa.Column('winner', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet', 'winner')
    op.drop_column('bet', 'status')
    # ### end Alembic commands ###
