"""empty message

Revision ID: ef514f83e021
Revises: 6ee6fdf8d64c
Create Date: 2020-10-06 01:56:22.356658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef514f83e021'
down_revision = '6ee6fdf8d64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('winner_receiver', sa.String(length=20), nullable=True))
    op.add_column('bet', sa.Column('winner_sender', sa.String(length=20), nullable=True))
    op.alter_column('bet', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bet', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('bet', 'winner_sender')
    op.drop_column('bet', 'winner_receiver')
    # ### end Alembic commands ###
